


export const lang = {

   // server back-end
   successDbConnection: 'Uspesno povezan na databazu.',
   serverIsClosing: 'Server se gasi...',
   defaultSpawn: 'Default Spawn',
   defaultSpawnDescripiton: 'Default spawn pozicija gde se stvvorite pri registracija.',

   // success messages
   welcomeToServer: 'Dobrodošli na Midnight Roleplay ! Uživajte u igri.',
   characterCreated: 'Uspešno ste kreirali karaktera.',
   welcomeToRegister: 'Dobrodošli na Midnight Roleplay, uživajte u igri.',


   // error messages 
   characterAlreadyExist: 'Karakter sa tim imenom i prezimenom već postoji.',
   userNotFound: 'Korisnik nije pronadjen.',
   playerNotNear: 'Igrač nije u vašoj blizini.',
   minTwoHours: 'Potrebno vam je minimum dva sata igre.',
   itemDoesntExist: 'Taj predmet ne postoji.',
   userAlreadyExist: 'Korisnik sa tim serijskim brojem već postoji.',
   notAllowed: 'Niste ovlašteni za korišćenje ove komande.',
   notInVehicle: 'Niste se u vozilu.',
   notInSpecFaction: 'Niste član odredjene fakcije.',
   notInAnyFaction: 'Niste član ni jedne fakcije.',
   notInYourFaction: 'Igrač nije član Vaše fakcije.',
   notOnDuty: 'Niste na dužnosti.',
   notNearJob: 'Ne nalazite se u blizini posla',
   userDoesntExist: 'Korisničko ime nije pronadjeno.',
   incorrectPassword: 'Korisnička šifra nije tačna.',
   alreadyEmployed: 'Već ste zaposleni.', 
   jobAlreadyStarted: 'Već ste započeli posao.',
   youHaveMaximumHouses: 'Imate maksimalan broj kuća.',
   thereAreNoOrdersRightNow: 'Trenutno nema porudžbina.',
   notEmployed: 'Niste zaposleni.',
   jobNotStarted: 'Niste započeli posao.',
   unemployed: 'Niste zaposleni.',
   notSpecificJob: 'Nemate odredjeni posao.',
   orderNotCompleted: 'Niste dostavili kompletnu porudžbinu',
   itemNoDescription: 'Ovaj predmet nema opis.',
   notEnoughMoney: 'Nemate dovoljno novca.',
   notEnoughProducts: 'Nema dovoljno produkata.',
   alreadyOwned: 'Neko već poseduje ovaj objekat.',
   error: 'Došlo je do greške.',
   animDoesntExist: 'Animacija nije pronadjena',
   notOnPosition: 'Ne nalazite se na odredjenoj lokaciji.',
   youDontHaveVehicleKeys: 'Nemate ključeve od ovog vozila.',
   youDontHaveHouseKeys: 'Nemate ključeve od ove kuće.',
   youDontOwnAHouse: 'Ne posedujete ni jednu kuću.',
   alreadyWorking: 'Već radite.',
   invalidBussinesType: 'Nepoznat tip biznisa',
   cmdDoesntExist: 'Komanda ne postoji.',
   noFurnitureOwned: `Nemate ništa od nameštaja`,
   notNearGasPump: 'Ne nalazite se u blizini aparata za točenje goriva.',
   notNearGasStation: 'Ne nalazite se na benziskoj pumpi',
   alreadyInChannel: 'Već ste u nekoj frekvenciji !',
   notInChannel: 'Niste ni u jednoj frekvenciji.',
   youDontHave: 'Ne posedujete ',
   channelNotFound: 'Frekvencija ne postoji !',
   channelWrongPassword: 'Šifra frekvencije nije tačna !',
   channelTooShortPassword: 'Šifra frekvencije mora da ima minumu 4 karaktera!',
   channelAlreadyExists: 'Frekvencija već postoji !',
   vehiclePointIsNotFree: 'Nema trenutno mesta da bi vam dostavili vozilo.',
   notCarOwner: 'Ne posedujete ovo vozilo',
   houseAlreadyOwner: 'Ova kuća / stan već poseduje vlasnika.',
   thereIsNoPaycheck: 'Trenutno nema novca za isplatu.',
   notReadyForHarvest: 'Još nije vreme za branje.',
   notFactionLeader: 'Niste lider ove fakcije.',


   // help messages
   COMMAND_USAGE: 'Komanda: ',
   garbageJobStarted: 'Započeli ste posao Smećara, vaš zadatak je da idete od kontenjera do kontenjera i interaktirate sa njima na slovo Y.',
   garbageHowToStop: 'Završili ste rutu. Vratite vaše zaduženo vozilo na parkingu gde ste ga i uzeli, zatim /garbage stop na mestu gde ste i započeli kako bi ste bili isplaćeni.',
   dmgUsage: 'Department of Motor Vehicles <br>Korišćenje: /dmv',
   cmdSyntax: '<b>[KOMANDA]</b> ',
   press: 'Pritisnite',
   pleaseReconnect: 'Rekontektuje se na F1.',


   // info messages
   kickedFromFaction: 'Izbačeni ste iz fakcije',
   uKickedFromFaction: 'Izbacili ste igrača iz fakcije',
   dmvInstructorGoVehicle: 'Instruktor Vožnje: Okej, dobro ste prošli usmeni test, sada sledi vožnja, pratite me do vozila.',
   succesfullyJob: 'Uspešno ste se zaposlili kao ',
   noTxInNumberplate: 'Vaše vozilo nema prefiks TX u registarskim tablicama.',
   taximetrePriceRange: 'Cena je u rangu ',
   succefullyGetLicense: 'Uspešno ste prošli testove i praktični deo polaganja za ',
   taximetreSettedOn: 'Uspešno ste promenili cenu vožnje po minuti na ',
   personSays: ' kaže: ', 
   personSaysInVehicle: ' [vozilo] kaže: ',
   personIsInjured: 'Ova osoba je ranjena ',
   quitjob: 'Uspešno ste dali otkaz na poslu.',
   serverRestart: 'Server restart.',
   orderAlreadyProcessing: 'Dostava je već završena ili je u toku.',
   orderSucess: 'Uspešno ste završili dostavu, zaradili ste ',
   successfullyBuyedVehicle: 'Uspešno ste kupili vozilo !', 	
   typesAreInRange: 'Taj tip ne postoji, tipovi se kreću izmedju ',
   successfullyLocked: 'Uspešno ste zaključali ',
   successfullyUnlocked: 'Uspešno ste otključali ',
   youEnteredTaxiVehicle: 'Ušli ste u Taksi vozilo oznake ',
   pricePerMinute: ', sa cenom po minutu ',
   vehicle: 'Vozilo',
   engineOn: 'Upalili ste motor vozila.',   
   dmvNotWorking: 'Department of Motor Vehicles, radno vreme od 6 - 20h',
   engineOff: 'Ugasili ste motor vozila.',   
   jobVehicleReturnBack: 'Molimo vratite vaše zaduženo vozilo na parking gde ste ga i uzeli.',  
   doorsLocked: 'Zaključali ste vrata',
   doorsUnlocked: 'Otključali ste vrata',
   isLocked: 'Zaključano je',
   vehicleIsLocked: 'Ovo vozilo je zaključano.',
   houseSoldSuccesfully: 'Uspešno ste prodali kuću',
   houseItemLeft: 'Uspešno ste ostavili predmet u svoju kuću',
   houseItemTaken: 'Uzeli ste predmet iz svoje kuće',
   maxBussinesType: 'Maksimalni tip biznisa je',
   livePhotoFromServer: 'Uzivo slika sa servera',
   channelSuccesfullyCreated: 'Uspešno ste kreirali frekvenciju.',
   channelSuccesfullyDeleted: 'Uspešno ste izbrisali frekvenciju.',
   channelSuccesfullyEdited: 'Uredili ste frekvenciju.',
   channelSuccesfullyLeaved: 'Napustili ste frekvenciju',
   succesfullyJoinedChannel: 'Uspešno ste se pridružilii frekvenciji.',   
   carSold: 'Vozilo uspešno prodato',
   successfullyBuyedHouse: 'Uspešno ste kupili kuću / stan ',
   lastPosition: 'Zadnja pozicija',
   lastPositionDescription: 'Zadnja pozicija prethodnog napuštanja igre.', 
   carBought: 'Uspešno ste kupili vozilo',
   carAlreadyOwned: 'Ovo vozilo je već u nečijem vlasništvu',
   carParked: 'Uspešno ste parkirali vozilo',
   waitingForPayment: ' čeka za isplatu.',
   minimumPayAmount: 'Minimum 1$.',
   invitedToFaction: 'Pozvani ste da se pridružite fakciji ',
   toOpenBankMenu: 'Bankovne opcije',


   // others 
   and: ' i ', 
   times: ' puta',
   bank: 'Bank',
   dropsCoin: ' baca novčić i pada na ',
   coinResult: ['glavu', 'pismo'],
   pmFrom: 'PM od',
   pmTo: 'PM za',
   quetly: 'govori tiho',
   isShouting: 'se dere',
   whispering: 'Šapućete',
   isWhisperingU: 'vam šapuće',
   tiresTo: ' pokušava da ',
   tryEnd: [
      'uspeva', 'ne uspeva'
   ],

   moneyWithdraw: 'Podizanje',
   moneyDeposit: 'Depozit',

   itemAction: { 
      use: 'Koristi predmet',
      give: 'Daj predmet',
      equip: 'Opremi',
      split: 'Podeli predmet',
      drop: 'Baci predmet',
   },

   weathers: [
      '', 'Vedro', 'Oblaćno', 'Smog', 'Maglovito',
      '', 'Kišno', 'Oluja', 'Provedravanje', 'Neutralno', 
      'Sneg', 'Mećava', '', '', 'Halowed'
   ]
};
