


export const lang = {

   // server back-end
   successDbConnection: 'Successfully connected to database',
   serverIsClosing: 'Server se gasi...',
   defaultSpawn: 'Default Spawn',
   defaultSpawnDescripiton: 'Default spawn pozicija gde se stvvorite pri registracija.',

   // success messages
   welcomeToServer: 'Dobrodošli na Midnight Roleplay ! Uživajte u igri.',
   characterCreated: 'Uspešno ste kreirali karaktera.',
   welcomeToRegister: 'Dobrodošli na Midnight Roleplay, uživajte u igri.',
   accountCreated: 'Račun uspešno kreiran !',
   addedSuccesfully: ' je uspešno dodan.',
   succesfullyCreatedFaction: 'Uspešno ste kreirali fakciju ',
   rankSuccessfullyUpdated: 'Rank je uspešno ažuriran.',
   vehicleLoaded: 'Vozilo uspešno učitano.',
   uTeleportedVehicleToYou: 'Teleportovali ste vozilo do vas.',

   // error messages 
   characterAlreadyExist: 'Karakter sa tim imenom i prezimenom već postoji.',
   userNotFound: 'Korisnik nije pronadjen.',
   playerNotNear: 'Igrač nije u vašoj blizini.',
   minTwoHours: 'Potrebno vam je minimum dva sata igre.',
   productNotAvailable: ' nije dostupan',
   itemDoesntExist: 'Taj predmet ne postoji.',
   noVehicleFound: 'Vozilo nije pronadjeno.',
   vehicleAlreadySpawned: 'Vozilo sa tim ID-om je već učitano.',
   userAlreadyExist: 'Korisnik sa tim serijskim brojem već postoji.',
   notAllowed: 'Niste ovlašteni za korišćenje ove komande.',
   noInventorySpaceForItems: 'Nemate dovoljno prostora u inventaru.',
   playerAlreadyInFaction: 'Igrač je već u nekoj fakciji.',
   playerAlreadyHasOffer: 'Igrač već ima neku ponudu.',
   weAreSoryBut: 'Žao nam je, ali ',
   rankNameCannotBeLessThenTreeSamirGey: 'Ime ranka ne sme biti kraće od 3 karaktera.',
   notInVehicle: 'Niste se u vozilu.',
   productAlreadyExist: 'Produkat već postoji.',
   notInSpecFaction: 'Niste član odredjene fakcije.',
   notInAnyFaction: 'Niste član ni jedne fakcije.',
   notInYourFaction: 'Igrač nije član vaše fakcije.',
   rankDoesntExist: 'Taj rank nije pronadjen.',
   notOnDuty: 'Niste na dužnosti.',
   vehicleNotSpawned: 'Vozilo nije stvoren.',
   notNearbyExit: 'Ne nalazite se u blizini vrata za izlazak.',
   factionNotFound: 'Fakcija nije pronadjena.',
   busiensAlreadyOwner: 'Ovaj biznis je već u nečijem vlasništvu.',
   notNearJob: 'Ne nalazite se u blizini posla',
   cannotToYourself: 'Ne možete saMI sebi.',
   cannotManageThisBusiness: 'Ne možete upravljati ovim biznisom.',
   cannotLeader: 'Nije moguće lidera fakcije.',
   userDoesntExist: 'Korisničko ime nije pronadjeno.',
   incorrectPassword: 'Korisnička šifra nije tačna.',
   youReachedMaxEquipemnt: 'Limit opremljenih predmeta je ',
   youAlreadyEquiped: 'Već imate opremljen ',
   cannotInVehicle: 'Nije moguće u vozilu.',
   alreadyEmployed: 'Već ste zaposleni.', 
   jobAlreadyStarted: 'Već ste započeli posao.',
   cannotWhileDead: 'Nije moguće dok ste mrtvi.',
   noFactionPermissions: 'Vaš rank fakcije nema te permisije.',
   youHaveMaximumHouses: 'Imate maksimalan broj kuća.',
   notNearBusiness: 'Ne nalazite se u blizini biznisa.',
   thereAreNoOrdersRightNow: 'Trenutno nema porudžbina.',
   youHaveMoreThanHealth: 'Vaš HP je dovoljnno visok za korišćenje medkita.',
   notEmployed: 'Niste zaposleni.',
   jobNotStarted: 'Niste započeli posao.',
   unemployed: 'Niste zaposleni.',
   notSpecificJob: 'Nemate odredjeni posao.',
   orderNotCompleted: 'Niste dostavili kompletnu porudžbinu',
   itemNoDescription: 'Ovaj predmet nema opis.',
   notEnoughMoney: 'Nemate dovoljno novca.',
   notEnoughtMoneyForVehicle: 'Nemate dovoljno novca za kupovinu ovog vozila.',
   notEnoughProducts: 'Nema dovoljno produkata.',
   alreadyOwned: 'Neko već poseduje ovaj objekat.',
   error: 'Došlo je do greške.',
   animDoesntExist: 'Animacija nije pronadjena',
   notOnPosition: 'Ne nalazite se na odredjenoj lokaciji.',
   noFirstAidNearby: 'Nema prve pomoći u blizini.',
   aidKitMustBeNear: 'Prva pomoć mora biti bliža.',
   youDontHaveVehicleKeys: 'Nemate ključeve od ovog vozila.',
   youDontHaveHouseKeys: 'Nemate ključeve od ove kuće.',
   youDontHaveBusinesKeys: 'Nemate ključeve od ovog biznisa.',
   youDontOwnAHouse: 'Ne posedujete ni jednu kuću.',
   alreadyWorking: 'Već radite.',
   invalidBussinesType: 'Nepoznat tip biznisa',
   cmdDoesntExist: 'Komanda ne postoji.',
   noFurnitureOwned: `Nemate ništa od nameštaja`,
   notNearGasPump: 'Ne nalazite se u blizini aparata za točenje goriva.',
   notNearGasStation: 'Ne nalazite se na benziskoj pumpi',
   alreadyInChannel: 'Već ste u nekoj frekvenciji !',
   notInChannel: 'Niste ni u jednoj frekvenciji.',
   playerDoesntHaveMoney: 'Igrač nema dovoljno novca.',
   youDontHave: 'Ne posedujete ',
   channelNotFound: 'Frekvencija ne postoji !',
   channelWrongPassword: 'Šifra frekvencije nije tačna !',
   channelTooShortPassword: 'Šifra frekvencije mora da ima minumu 4 karaktera!',
   channelAlreadyExists: 'Frekvencija već postoji !',
   vehiclePointIsNotFree: 'Nema trenutno mesta da bi vam dostavili vozilo.',
   notCarOwner: 'Ne posedujete ovo vozilo',
   houseAlreadyOwner: 'Ova kuća / stan već poseduje vlasnika.',
   thereIsNoPaycheck: 'Trenutno nema novca za isplatu.',
   notReadyForHarvest: 'Još nije vreme za branje.',
   notFactionLeader: 'Niste lider ove fakcije.',
   unsuccessfulAuth: 'Neuspešna prijava',
   thisBusinessIsLocked: 'Biznis je zaključan, zavoren.',
   thisHouseIsLocked: 'Ova kuća je zaključana.',


   // help messages
   COMMAND_USAGE: 'Komanda: ',
   garbageJobStarted: 'Započeli ste posao Smećara, vaš zadatak je da idete od kontenjera do kontenjera i interaktirate sa njima na slovo Y.',
   garbageHowToStop: 'Završili ste rutu. Vratite vaše zaduženo vozilo na parkingu gde ste ga i uzeli, zatim /garbage stop na mestu gde ste i započeli kako bi ste bili isplaćeni.',
   dmgUsage: 'Department of Motor Vehicles <br>Korišćenje: /dmv',
   cmdSyntax: '<b>[KOMANDA]</b> ',
   press: 'Pritisnite',
   pleaseReconnect: 'Rekontektuje se na F1.',
   toOpenBusinessMenu: 'Da otvorie meni biznisa',
   toEnterBusiness: 'Da udjete u biznis',
   toBuyTheBusinenss: 'Da kupite biznis',
   businessManagement: 'Opcije vašeg biznisa',


   // info messages
   kickedFromFaction: 'Izbačeni ste iz fakcije',
   uKickedFromFaction: 'Izbacili ste ',
   fromFaction: ' iz fakcije.',
   dmvInstructorGoVehicle: 'Instruktor Vožnje: Okej, dobro ste prošli usmeni test, sada sledi vožnja, pratite me do vozila.',
   succesfullyJob: 'Uspešno ste se zaposlili kao ',
   noTxInNumberplate: 'Vaše vozilo nema prefiks TX u registarskim tablicama.',
   taximetrePriceRange: 'Cena je u rangu ',
   succefullyGetLicense: 'Uspešno ste prošli testove i praktični deo polaganja za ',
   taximetreSettedOn: 'Uspešno ste promenili cenu vožnje po minuti na ',
   uLeavedFaction: 'Napustili ste fakciju ',
   businesNoVehiclesToSell: 'Ovaj salon vozila nema trenutno vozila u ponudi.',
   succesfullySoldBizToCountry: 'Uspešno ste pridali biznis državi.',
   youDisarmedPlayer: 'Razoružali ste igrača',
   uLeaveFactionLeaderPosition: 'Napustili ste fakciju i poziciju lidera fakcije ',
   personSays: ' kaže: ', 
   personSaysInVehicle: ' [vozilo] kaže: ',
   personIsInjured: 'Ova osoba je ranjena ',
   uUnlockedVehicle: 'Vozilo otključano.',
   uLockedVehicle: 'Vozilo zaključano.',
   quitjob: 'Uspešno ste dali otkaz na poslu.',
   serverRestart: 'Server restart.',
   hasKickedYouFromFaction: ' vas je izbacio iz fakcije ',
   orderAlreadyProcessing: 'Dostava je već završena ili je u toku.',
   toJoinFaction: ' vas je pozvao da se pridružite fakciji ',
   uSetLeaderOf: 'Dali ste lidera fakcije ',
   businessLocked: 'Zaključali ste biznis.',
   uAreNowLeaderOf: 'Postavljeni ste za lidera ',
   givesSomeMoney: 'daje nešto novca',
   businessUnlocked: 'Otključali ste biznis.',
   chatIsClearedBy: 'Čet očišćen od strane administratora ',
   uAreNotLeaderAnymore: 'Skinut vam je lider ',
   orderSucess: 'Uspešno ste završili dostavu, zaradili ste ',
   successfullyBuyedVehicle: 'Uspešno ste kupili vozilo !', 	
   successfullyBuyedBusiness: 'Uspešno ste kupili biznis ',
   typesAreInRange: 'Taj tip ne postoji, tipovi se kreću izmedju ',
   successfullyLocked: 'Uspešno ste zaključali ',
   successfullyUnlocked: 'Uspešno ste otključali ',
   disarmedYou: ' vam je oduzeo oružija.',
   youEnteredTaxiVehicle: 'Ušli ste u Taksi vozilo oznake ',
   pricePerMinute: ', sa cenom po minutu ',
   vehicle: 'Vozilo',
   engineOn: 'Upalili ste motor vozila.',   
   dmvNotWorking: 'Department of Motor Vehicles, radno vreme od 6 - 20h',
   engineOff: 'Ugasili ste motor vozila.',   
   dealershipNoPreview: 'Auto salon nema izložbeno mesto.',
   jobVehicleReturnBack: 'Molimo vratite vaše zaduženo vozilo na parking gde ste ga i uzeli.',  
   doorsLocked: 'Zaključali ste vrata',
   yourFactionInvite: ' vaš zahtev za pridruživanje fakciji.',
   doorsUnlocked: 'Otključali ste vrata',
   isLocked: 'Zaključano je',
   vehicleIsLocked: 'Ovo vozilo je zaključano.',
   houseSoldSuccesfully: 'Uspešno ste prodali kuću',
   houseItemLeft: 'Uspešno ste ostavili predmet u svoju kuću',
   houseItemTaken: 'Uzeli ste predmet iz svoje kuće',
   maxBussinesType: 'Maksimalni tip biznisa je',
   livePhotoFromServer: 'Uzivo slika sa servera',
   thereIsNoFactionsRn: 'Trenutno nije napravljena niti jedna fakcija.',
   channelSuccesfullyCreated: 'Uspešno ste kreirali frekvenciju.',
   channelSuccesfullyDeleted: 'Uspešno ste izbrisali frekvenciju.',
   channelSuccesfullyEdited: 'Uredili ste frekvenciju.',
   channelSuccesfullyLeaved: 'Napustili ste frekvenciju',
   succesfullyJoinedChannel: 'Uspešno ste se pridružilii frekvenciji.',   
   carSold: 'Vozilo uspešno prodato',
   successfullyBuyedHouse: 'Uspešno ste kupili kuću / stan ',
   lastPosition: 'Zadnja pozicija',
   lastPositionDescription: 'Zadnja pozicija prethodnog napuštanja igre.', 
   carBought: 'Uspešno ste kupili vozilo',
   carAlreadyOwned: 'Ovo vozilo je već u nečijem vlasništvu',
   carParked: 'Uspešno ste parkirali vozilo',
   waitingForPayment: ' čeka za isplatu.',
   minimumPayAmount: 'Minimum 1$.',
   invitedToFaction: 'Pozvani ste da se pridružite fakciji ',
   toOpenBankMenu: 'Bankovne opcije',
   factionRankDelete: 'Rank uspešno izbrisan.',
   uDeclinedFactionInvite: 'Odbili ste zahtev za pridruživanje fakciji.',
   uAcceptedFactionInvite: 'Prihvatili ste zahtev za pridruživanje fakciji.',

   // warnings
   adminWarnedYou: 'vas je upozorio',


   // others 
   and: ' i ', 
   times: ' puta',
   dispatcher: 'DISPATCHER',
   factionInvite: 'Faction Invite',
   bank: 'Bank',
   dropsCoin: ' baca novčić i pada na ',
   coinResult: ['glavu', 'pismo'],
   pmFrom: 'PM od',
   pmTo: 'PM za',
   quetly: 'govori tiho',
   accepted: ' je prihvatio ',
   underId: ' pod brojem ',
   declined: ' je odbio ',
   isShouting: 'se dere',
   putCuffs: ' stavlja lisice ',
   removeCuffs: ' skida lisice ',
   fromAdmin: ' od strane administratora ',
   ownedHouse: 'Kuća ',
   account: 'Račun',
   for: ' za ',
   yourHouse: 'Vaša kuća / stan/',
   social: 'RGSC',
   hardwer: 'Hardver',
   IP: 'IP Adresa',
   product: 'Produkat ',
   whispering: 'Šapućete',
   admin: 'Admin',
   isWhisperingU: 'vam šapuće',
   unranked: 'Unranked',
   tiresTo: ' pokušava da ',
   tryEnd: [
      'uspeva', 'ne uspeva'
   ],

   moneyWithdraw: 'Podizanje',
   moneyDeposit: 'Depozit',

   itemAction: { 
      use: 'Koristi predmet',
      give: 'Daj predmet',
      EQUIP: 'Opremi',
      CONSUME: 'Konzumiraj',
      split: 'Podeli predmet',
      drop: 'Baci predmet',
   },

   weathers: [
      '', 'Vedro', 'Oblaćno', 'Smog', 'Maglovito',
      '', 'Kišno', 'Oluja', 'Provedravanje', 'Neutralno', 
      'Sneg', 'Mećava', '', '', 'Halowed'
   ]
};
