

export default [

   {
      name: 'Walls',
      price: 200,
      objects: [
         'soupsint1',
         'soupsint2',
         'soupsint3',
         'soupsint4',
         'soupsint5',
         'soupsint6',
         'soupsint7',
         'soupsint8',
         'soupsint9',
         'soupsint10',
         'soupsint11',
         'soupsint12',
         'soupsint13',
         'soupsint14',
         'soupsint15',
         'soupsint16',
         'soupsint17',
         'soupsint18',
         'soupsint19',
         'soupsint20',
         'souplight1',
         'souplight2',
         'souplight3',
         'souplight4',
         'souplight5',
         'souplight6',
         'souplight7',
         'soupsint21_pt1',
         'soupsint21_pt2',
         'soupsint22_pt1',
         'soupsint22_pt2',
         'soupsint23_pt1',
         'soupsint23_pt2',
         'soupsint23_pt3',
         'soupsint23_pt4',
         'soupsint24_pt1',
         'soupsint24_pt2',
         'soupsint25',
         'soupsint26',
         'soupsint27',
         'soupsint28',
         'soupsint29',
         'soupsint30_dt_pt1',
         'soupsint30_dt_pt2',
         'soupsint30_dt_pt3',
         'soupsint30_pt1',
         'soupsint30_pt2',
         'soupsint30_pt3',
         'soupsint30_pt4',
         'soupemptybox001',
         'soupemptybox002',
         'soupemptybox003',
         'souplightbold1',
         'souplightbold2',
         'souplightbold3',
         'souplightbold4',
         'souplightbold5',
         'souplightbold6',
         'souplightbold7',
         'souplongwall001',
         'souplongwall002',
         'souplongwall003',
         'souplongwall004',
         'souplongwall005',
         'souplongwall006',
         'souplongwall007',
         'souplongwall008',
         'souplongwall009',
         'souplongwall010',
         'souplongwall011',
         'souplongwall012',
         'souplongwall013',
         'souplongwall014',
         'souplongwall015',
         'souplongwall016',
         'souplongwall017',
         'souplongwall018',
         'souplongwall019',
         'souplongwall020',
         'souplongwall021',
         'souplongwall022',
         'souplongwall023',
         'souplongwall024',
         'souplongwall025',
         'souplongwall026',
         'souplongwall027',
         'souplongwall028',
         'souplongwall029',
         'souplongwall030',
         'souplongwall031',
         'souplongwall032',
         'souplongwall033',
         'souplongwall034',
         'souplongwall035',
         'souplongwall036',
         'souplongwall037',
         'souplongwall038',
         'souplongwall039',
         'souplongwall040',
         'souplongwall041',
         'soupdoorwall001',
         'soupdoorwall002',
         'soupdoorwall003',
         'soupdoorwall004',
         'soupdoorwall005',
         'soupdoorwall006',
         'soupdoorwall007',
         'soupdoorwall008',
         'soupdoorwall009',
         'soupdoorwall010',
         'soupdoorwall011',
         'soupdoorwall012',
         'soupdoorwall013',
         'soupdoorwall014',
         'soupdoorwall015',
         'soupdoorwall016',
         'soupdoorwall017',
         'soupdoorwall018',
         'soupdoorwall019',
         'soupdoorwall020',
         'soupdoorwall021',
         'soupdoorwall022',
         'soupdoorwall023',
         'soupdoorwall024',
         'soupdoorwall025',
         'soupdoorwall026',
         'soupdoorwall027',
         'soupdoorwall028',
         'soupdoorwall029',
         'soupdoorwall030',
         'soupdoorwall031',
         'soupdoorwall032',
         'soupdoorwall033',
         'soupdoorwall034',
         'soupdoorwall035',
         'soupdoorwall036',
         'soupdoorwall037',
         'soupdoorwall038',
         'soupdoorwall039',
         'soupdoorwall040',
         'soupdoorwall041',
         'souphalfwall001',
         'souphalfwall002',
         'souphalfwall003',
         'souphalfwall004',
         'souphalfwall005',
         'souphalfwall006',
         'souphalfwall007',
         'souphalfwall008',
         'souphalfwall009',
         'souphalfwall010',
         'souphalfwall011',
         'souphalfwall012',
         'souphalfwall013',
         'souphalfwall014',
         'souphalfwall015',
         'souphalfwall016',
         'souphalfwall017',
         'souphalfwall018',
         'souphalfwall019',
         'souphalfwall020',
         'souphalfwall021',
         'souphalfwall022',
         'souphalfwall023',
         'souphalfwall024',
         'souphalfwall025',
         'souphalfwall026',
         'souphalfwall027',
         'souphalfwall028',
         'souphalfwall029',
         'souphalfwall030',
         'souphalfwall031',
         'souphalfwall032',
         'souphalfwall033',
         'souphalfwall034',
         'souphalfwall035',
         'souphalfwall036',
         'souphalfwall037',
         'souphalfwall038',
         'souphalfwall039',
         'souphalfwall040',
         'soupwall001',
         'soupwall002',
         'soupwall003',
         'soupwall004',
         'soupwall005',
         'soupwall006',
         'soupwall007',
         'soupwall008',
         'soupwall009',
         'soupwall010',
         'soupwall011',
         'soupwall012',
         'soupwall013',
         'soupwall014',
         'soupwall015',
         'soupwall016',
         'soupwall017',
         'soupwall018',
         'soupwall019',
         'soupwall020',
         'soupwall021',
         'soupwall022',
         'soupwall023',
         'soupwall024',
         'soupwall025',
         'soupwall026',
         'soupwall027',
         'soupwall028',
         'soupwall029',
         'soupwall030',
         'soupwall031',
         'soupwall032',
         'soupwall033',
         'soupwall034',
         'soupwall035',
         'soupwall036',
         'soupwall037',
         'soupwall038',
         'soupwall040',
         'soupwall041',
         'soupwall042',
         'soupwindwall01',
         'soupwindwall002',
         'soupwindwall003',
         'soupwindwall004',
         'soupwindwall005',
         'soupwindwall006',
         'soupwindwall007',
         'soupwindwall008',
         'soupwindwall009',
         'soupwindwall010',
         'soupwindwall011',
         'soupwindwall012',
         'soupwindwall013',
         'soupwindwall014',
         'soupwindwall015',
         'soupwindwall016',
         'soupwindwall017',
         'soupwindwall018',
         'soupwindwall019',
         'soupwindwall020',
         'soupwindwall021',
         'soupwindwall022',
         'soupwindwall023',
         'soupwindwall024',
         'soupwindwall025',
         'soupwindwall026',
         'soupwindwall027',
         'soupwindwall028',
         'soupwindwall029',
         'soupwindwall030',
         'soupwindwall031',
         'soupwindwall032',
         'soupwindwall033',
         'soupwindwall034',
         'soupwindwall035',
         'soupwindwall036',
         'soupwindwall037',
         'soupwindwall038',
         'soupwindwall039',
         'soupwindwall040',
         'soupwindwall041',
         'Soupfloor001',
         'Soupfloor002',
         'Soupfloor003',
         'Soupfloor004',
         'Soupfloor005',
         'Soupfloor006',
         'Soupfloor007',
         'Soupfloor008',
         'Soupfloor009',
         'Soupfloor010',
         'Soupfloor011',
         'Soupfloor012',
         'Soupfloor013',
         'Soupfloor014',
         'Soupfloor015',
         'Soupfloor016',
         'Soupfloor017',
         'Soupfloor018',
         'Soupfloor019',
         'Soupfloor020',
         'Soupfloor021',
         'Soupfloor022',
         'Soupfloor023',
         'Soupfloor024',
         'Soupfloor025',
         'Soupfloor026',
         'Soupfloor027',
         'Soupfloor028',
         'Soupfloor029',
         'Soupfloor030',
         'Soupfloor031',
         'Soupfloor032',
         'Soupfloor033',
         'Soupfloor034',
         'Soupfloor035',
         'Soupfloor036',
         'Souproof001',
         'Souproof002',
         'Souproof003',
         'soupdoortrim001',
         'soupdoortrim002',
         'soupdoortrim003',
         'soupdoortrim004',
         'souphalftrim001',
         'souphalftrim002',
         'souphalftrim003',
         'souphalftrim004',
         'souplongtrim001',
         'souplongtrim002',
         'souplongtrim003',
         'souplongtrim004',
         'souptrim001',
         'souptrim002',
         'souptrim003',
         'souptrim004',
         'Soupnewstairs001',
         'Soupnewstairs002',
         'Soupnewstairs003',
         'Soupnewstairs004',
         'Soupnewstairs005',
         'Soupnewstairs006',
         'Soupnewstairs007',
         'Soupnewstairs008',
         'Soupstairs001',
         'Soupstairs002',
         'Soupstairs003',
         'Soupstairs004',
         'Soupstairs005',
         'Soupstairs006',
         'Soupstairs007',
         'Soupstairs008',
         'soupwarehouse001_pt1',
         'soupwarehouse001_pt2',
         'sps2int1',
         'sps2int2',
         'sps2int3',
         'sps2int4',
         'sps2int5',
         'sps2int6',
         'sps2int6_pt2',
         'sps2int7',
         'sps2int8',
         'sps2int9',
         'sps2int10',
         'sps2int11',
         'sps2int12',
         'sps2int13',
         'sps2int14',
         'sps2int15',
         'sps2int8_pt2',
         'sps2int12_pt2',
         'sps2int12_pt3',
         'sps2int12_pt4',
         'sps2int12_pt5',
         'sps2int16',
         'sps2int17',
         'sps2int18',
         'sps2int19',
         'sps2int20',
         'sps2int21',
         'sps2int22',
         'sps2int23',
         'sps2int24'
      ]
   },
   
   {
      name: 'Doors',
      price: 100,
      objects: [
         'hei_v_ilev_fh_heistdoor1', 'hei_v_ilev_fh_heistdoor2', 'v_ilev_cor_offdoora', 'v_ilev_fa_frontdoor', 'v_ilev_fa_roomdoor', 'v_ilev_fa_warddoorr', 'v_ilev_fh_bedrmdoor', 'v_ilev_fh_door01',
         'v_ilev_fh_door02', 'v_ilev_fh_door5', 'v_ilev_fh_frntdoor', 'v_ilev_fh_frontdoor', 'v_ilev_fib_door1', 'v_ilev_fib_door3', 'v_ilev_fib_doorbrn', 'v_ilev_frnkwarddr2', 'v_ilev_housedoor1',
         'v_ilev_j2_door', 'v_ilev_mm_door', 'v_ilev_mm_doordaughter', 'v_ilev_mm_doorm_l', 'v_ilev_mm_doorm_r', 'v_ilev_mm_doorw', 'v_ilev_mp_high_frontdoor', 'v_ilev_mp_low_frontdoor', 'v_ilev_mp_mid_frontdoor',
         'v_ilev_ph_cellgate', 'v_ilev_ph_door002', 'v_ilev_ph_door01', 'v_ilev_ph_gendoor', 'v_ilev_ph_gendoor002', 'v_ilev_ph_gendoor003', 'v_ilev_ra_door1_l', 'v_ilev_ra_door1_r', 'v_ilev_ra_door2',
         'v_ilev_ra_door3', 'v_ilev_ra_door4l', 'v_ilev_ra_door4r', 'v_ilev_rc_door2', 'v_ilev_roc_door4', 'v_ilev_sol_off_door01', 'v_ilev_trev_door', ''
      ]
   },

   {
      name: 'Pillars',
      price: 150,
      objects: [
         'prop_ld_dstpillar_04', 'prop_ld_dstpillar_06', 'prop_ld_dstpillar_08', 'prop_ld_dstpillar_05', 'prop_ld_lab_corner01', 'prop_fib_morg_cnr01', 'prop_ld_dstpillar_07',
         'prop_ld_dstpillar_01',
      ]
   },

   {
      name: 'Fences',
      price: 500,
      objects: [

      ]
   },

   {
      name: 'Lighting',
      price: 150,
      objects: [
         'apa_mp_h_lit_lamptable_005', 'apa_mp_h_lit_lamptable_02', 'apa_mp_h_lit_lamptable_04', 'apa_mp_h_lit_lamptable_09', 'apa_mp_h_lit_lamptable_21', 'apa_mp_h_lit_lamptablenight_16',
         'apa_mp_h_lit_lamptablenight_24', 'apa_mp_h_yacht_table_lamp_01', 'apa_mp_h_yacht_table_lamp_03', 'prop_ld_cont_light_01', 'prop_wall_light_05a', 'prop_wall_light_14b', 'prop_wall_light_14a',
         'prop_wall_light_17a', ''
      ]
   },

   {
      name: 'Pictures',
      price: 80,
      objects: [

      ]
   },

   {
      name: 'Sofas',
      price: 200,
      objects: [
         'p_lev_sofa_s', 'apa_mp_h_stn_sofa_daybed_01'
      ]
   },

   {
      name: 'Glass',
      priec: 600,
      objects: [
         'hei_prop_yah_glass_01', 'hei_prop_yah_glass_02', 'hei_prop_yah_glass_03', 'hei_prop_yah_glass_04', 'hei_prop_yah_glass_05', 'hei_prop_yah_glass_06', 'hei_prop_yah_glass_07',
         'hei_prop_yah_glass_08', 'hei_prop_yah_glass_09', '',
      ]
   },

   {
      name: 'Kitchen',
      price: 400,
      objects: [

      ]
   },

   {
      name: 'Tables',
      price: 175,
      objects: [
         'apa_mp_h_din_table_01', 'apa_mp_h_din_table_04', 'apa_mp_h_din_table_06', 'apa_mp_h_din_table_11', 'bkr_prop_fakeid_table'
      ]
   },

   {
      name: 'Storages',
      objects: [
         'apa_mp_h_bed_chestdrawer_02', 'hei_heist_bed_chestdrawer_04'
      ]
   },

   {
      name: 'Beds',
      price: 200,
      objects: [
         'apa_mp_h_bed_with_table_02', 'apa_mp_h_bed_double_08', 'apa_mp_h_bed_double_09', 'apa_mp_h_bed_with_table_02', 'apa_mp_h_yacht_bed_02', 'hei_heist_bed_double_08'
      ]
   },

   {
      name: 'Chairs',
      price: 110,
      objects: [

      ]
   },

   {
      name: 'Nature',
      price: 125,
      objects: [
         'prop_plant_interior_05a', 'prop_pot_plant_02c', 'prop_plant_int_05b', 'prop_pot_plant_05d', 'prop_plant_int_03a', 'prop_pot_plant_02b', 'prop_pot_plant_inter_03a', 'prop_pot_plant_04c',
         'prop_plant_int_03c', 'prop_plant_int_05a', 'prop_pot_plant_01a', 'prop_plant_int_02a', 'prop_plant_int_06a', 'prop_pot_plant_04a', 'prop_plant_int_01a', 'prop_pot_plant_02a', 'prop_plant_int_06c',
         'prop_plant_int_04c', 'prop_pot_plant_05a', 'prop_pot_plant_03c', 'prop_plant_int_02b', 'prop_pot_plant_03a', 'prop_pot_plant_01e', 'prop_pot_plant_05d_l1', 'prop_pot_plant_01d', 'prop_pot_plant_02d',
         'prop_pot_plant_01b', 'prop_pot_plant_bh1', 'prop_pot_plant_01c', 'prop_bush_ivy_02_pot', 'prop_bush_ivy_01_l', 'prop_bush_ivy_01_top'
      ]
   }

]