global.DEALERSHIP_VEHICLES = [ 
   MOTORCYCLES = [
      { model: 'akuma', price: 3000, name: 'Akuma' },
      { model: 'avarus', price: 3000, name: 'Avarus' },
      { model: 'bagger', price: 3000, name: 'Bagger' },
      { model: 'bati', price: 3000, name: 'Batian' },
      { model: 'bati2', price: 3000, name: 'Batian 2' },
      { model: 'bf400', price: 3000, name: 'BF-400' },
      { model: 'carbonrs', price: 3000, name: 'Carbon RS' },
      { model: 'cliffhanger', price: 3000, name: 'Cliff Hanger' },
      { model: 'daemon', price: 3000, name: 'Daemon' },
      { model: 'daemon2', price: 3000, name: 'Daemon 2' },
      { model: 'defiler', price: 3000, name: 'Defiler' },
      { model: 'deathbike', price: 3000, name: 'Deathbike' },
      { model: 'diablous', price: 3000, name: 'Diablous' },
      { model: 'diablous2', price: 3000, name: 'Diablous 2' },
      { model: 'double', price: 3000, name: 'Double' },
      { model: 'enduro', price: 3000, name: 'Enduro' },
      { model: 'esskey', price: 3000, name: 'Esskey' },
      { model: 'faggio', price: 3000, name: 'Faggio'  },
      { model: 'faggio2', price: 3000, name: 'Faggio 2' },
      { model: 'faggio3', price: 3000, name: 'Faggio 3' },
      { model: 'fcr', price: 3000, name: 'FCR-900' },
      { model: 'fcr2', price: 3000, name: 'FCR-900 2' },
      { model: 'gargoyle', price: 3000, name: 'Gargoyle' },
      { model: 'hakuchou', price: 3000, name: 'Hakucho' },
      { model: 'hexer', price: 3000, name: 'Hexer' },
      { model: 'innovation', price: 3000, name: 'Innovation' },
      { model: 'lectro', price: 3000, name: 'Lectro' },
      { model: 'enduro', price: 3000, name: 'Enduro' },
      { model: 'manchez', price: 3000, name: 'Manchez' },
      { model: 'nemesis', price: 3000, name: 'Nemesis' },
      { model: 'nightblade', price: 3000, name: 'Nightblade' },
      { model: 'pcj', price: 3000, name: 'PCJ' },
      { model: 'ratbike', price: 3000, name: 'Ratbike' },
      { model: 'ruffian', price: 3000, name: 'Ruffian' },
      { model: 'sanchez', price: 3000, name: 'Sanchez' },
      { model: 'sanchez2', price: 3000, name: 'Sanchez2' },
      { model: 'sanctus', price: 3000, name: 'Sanctus' },
      { model: 'sovereign', price: 3000, name: 'Sovereign' },
      { model: 'stryder', price: 3000, name: 'Stryder' },
      { model: 'thrust', price: 3000, name: 'Thrust' },
      { model: 'vader', price: 3000, name: 'Vader' },
      { model: 'vindicator', price: 3000, name: 'Vindicator' },
      { model: 'vortex', price: 3000, name: 'Vortex' }, 
      { model: 'wolfsbane', price: 3000, name: 'Wolfsbane' },
      { model: 'zombiea', price: 3000, name: 'Zombie Bobber' },
      { model: 'zombieb', price: 3000, name: 'Zombie Chopper' },
      { model: 'manchez2', price: 3000, name: 'Manchez Scout' },
   ],

   OFFROADS = [ 

   ],

   CYCLES = [ 
      { model: 'bmx', price: 3000, name: 'BMX' },
      { model: 'cruiser', price: 3000, name: 'Cruiser' },
      { model: 'fixter', price: 3000, name: 'Fixter' },
      { model: 'scorcher', price: 3000, name: 'Scorcher' },
      { model: 'tribike', price: 3000, name: 'Whippet Race Bike' },
      { model: 'tribike2', price: 3000, name: 'Endurex Race Bike' },
      { model: 'tribike3', price: 3000, name: 'Tri-Cycles Race Bike' }
   ]
]
   