


export enum itemType {
   EQUIPABLE, CONSUMABLE, OPENABLE, 
   DRINK, FOOD, DRUG, WEAPON, AMMO,
   ILEGAL, LEGAL, MISC, CLOTHING,
   PROP, HEAVY, STACKABLE, USABLE, STORAGE, 
   SEED, DOCUMENT, LICENSE, COOKABLE, COOKER,
   ID_CARD, LAW_BADGE, CREDIT_CARD
}

export enum itemEntity { 
   PLAYER, BACKPACK, STORAGE,
   VEHICLE, TEMPORARY_VEHICLE,
   HOUSE, BUSINESS, NONE
}

export enum itemStatus { 
   NONE, RAW, COOKED, BROKEN, FURNITURE_PLACED
}