enum HeadDisplayFlag {
   TEXTWITHOUTLINE = 0,
   NONEEMPTY,
   HEALTHBAR,
   AUDIOSPEAKER,
   FLAGORPAUSED,
   FLAG,
   PASSIVEMODE,
   WANTEDSTAR,
   STEERINGWHEEL,
   HEADSET,
   HIGHLIGHTPLAYER,
   TEXTNOOUTLINE,
   ARROWDOWN,
   BREIFCASE,
   LITTLEUSER,
   RANKNUMBER,
   VOICEINDICATOR
};